### ISSUE TITLE
[version-01] ISIS is not yet included in routing protocols

### ISSUE THREAD

**Issue by alexaguado** [IETF-OPSAWG-WG/l3nm#1]
This shall be included ASAP (in the next version)

**Comment by oscargdd** [comment]
As there is currently no use case and no RFC on the use of IS-IS for CE-PE routing protocol, the issue is closed

**Comment by sbarguil** [comment]
We have found a UC that requires this kind of support. Two PE routers running inside the same network, create an ISIS adjacency inside the VPN to share the multicast routing information.

**Comment by oscargdd** [comment]
Closed with pull request #56
