### ISSUE TITLE
Nits in Section 4 intro para

### ISSUE THREAD

**Issue by PhilipEardley** [IETF-OPSAWG-WG/l3nm#10]
The opening para refers to Section 4 and S4.4 - should these be S3? It also refers to BESS-L3VPN, which isn't mentioned elsewhere in the draft

**Comment by oscargdd** [comment]
Text has been updated in -01 versión. Please review and check if the nits still apply

**Comment by oscargdd** [comment]
Philip, were you able to check the new test?

**Comment by oscargdd** [comment]
A reference to BESS document Will be added in section 5.  Relation with other YANG Models, under "Device Modules:  L3NM is not a device model"

**Comment by boucadair** [comment]
Are you referring to: https://datatracker.ietf.org/doc/draft-ietf-bess-l3vpn-yang/?

That one expired. I don't see the need to cite it.

**Comment by oscargdd** [comment]
As the document is expired, it will not be cited.
