### ISSUE TITLE
DHCP relay agent Servers from the whole service 

### ISSUE THREAD

**Issue by segevere** [IETF-OPSAWG-WG/l3nm#109]
Provider's DHCP is configured per IP connection per vpn-network-accesses.

However in most L3VPN setups there are upto two DHCP servers which applied to the complete service and per vpn-network-accesses-->IP connection  it need to be set.

so instead of the current design , how about :
1) define DHCP relay agent servers (IPv4 and or IPv6) per vpn-service
2)  add enable/disable IPv4/IPv6 DHCP relay per vpn-network-accesses-->IP connection , the the controller sets the 'DHCP relay agent servers ' defined per vpn-service

**Comment by boucadair** [comment]
Hi Erez, 

I guess you are referring to provider-dhcp not dhcp-realy case. No? 

The information will be needed to be present at the level of the network-access. So having the server defined at the service level won't be useful unless the allocation-type at the network-access level is a set appropriately.

I agree this can be factorized, but is there a value in defining the servers at the service level independently of the type per network-access?

Thank you.

**Comment by segevere** [comment]
Hi,

I'm talking about DHCP relay, in DHCP relay there is a need to define list of DHCP servers to be relay the DHCP traffic to them.  
probably I meant customer-dhcp-servers to be defined in service level in order not to duplicated ti information per network-access .

Thanks,
Erez

**Comment by boucadair** [comment]
> 
> 
> Hi,
> 
> I'm talking about DHCP relay, in DHCP relay there is a need to define list of DHCP servers to be relay the DHCP traffic to them.
> probably I meant customer-dhcp-servers to be defined in service level in order not to duplicated ti information per network-access .
> 
> Thanks,
> Erez

Thanks. 

Agree that customer-dhcp-servers are likely to be the same for all network accesses. We may define that information at the service level and a control parameter at the access level to inherit the service-level servers. Nevertheless, the presence of the servers at the service-level is meaningful only of an access control have the control parameter set to "true".  If we put it at the service level, which condition should be used to make sure the presence of the servers is meaningful?

The advantage I see in having this information at the network access level is that it can be easily conditioned by the allocation type.

**Comment by boucadair** [comment]
@segevere: Can we conclude this one?

**Comment by segevere** [comment]
@boucadair  yes :)

**Comment by boucadair** [comment]
Thanks, Erez.
