### ISSUE TITLE
Fix issues from  Tom Petch review in Opsawg mailing list

### ISSUE THREAD

**Issue by oscargdd** [IETF-OPSAWG-WG/l3nm#112]
Original message: 
https://mailarchive.ietf.org/arch/msg/opsawg/Mh-BCY9PZuWGE1QKzBD1rll6_AY/

Looking at the YANG module it would appear that a lot of prior knowledge is needed in order to understand it, such as QinQ, dot1Q, GRE, LDP, VRRP, etc etc ie they are what I think of as Normative References and yet I cannot recall seeing a YANG module with so few reference clauses; and the very few reference clauses that are there refer to RFC that do not appear in the I-D References.
I also note that the IANA Considerations registers a different prefix to that in the YANG module and it is unclear /*UNUSED*/ is about.  And examples in the body of the I-D rather than as an Informative appendix mmmm.  I am unenthusiastic about looking any deeper.
Tom Petch

**Comment by oscargdd** [comment]
Qin takes care of the references. Do the work after the Split of the module.
Oscar to take care of the editorial issue in IANA Section.

**Comment by oscargdd** [comment]
Daniel King takes the issue of looking at the best aproach for the examples

**Comment by boucadair** [comment]
> 
> 
> Daniel King takes the issue of looking at the best aproach for the examples

I would move this section to an appendix.

**Comment by boucadair** [comment]
@oscargdd: I would close this one as the only remaining point to check is references. We do already have an issue to track that.

**Comment by oscargdd** [comment]
all the points expect the references are solved. Issue #115 deals with the references
