### ISSUE TITLE
Routing policy vs forwarding policy difference

### ISSUE THREAD

**Issue by luciaob** [IETF-OPSAWG-WG/l3nm#113]
Hi,

On the global routing profiles, it should be a difference between routing and forwarding policies. Also, it would be needed to have a reference to prefix list, since currently there is no way to differentiate those policy profiles in L3NM model.

**Comment by sbarguil** [comment]
related to #18

**Comment by oscargdd** [comment]
Forwarding profile is included in pull request https://github.com/IETF-OPSAWG-WG/l3nm/pull/118  . Just a hook is added (no leafref).
