### ISSUE TITLE
Add reference and descriptions to identityrefs for protocol-type 

### ISSUE THREAD

**Issue by oscargdd** [IETF-OPSAWG-WG/l3nm#115]
typedef protocol-type;
Are you really sure that the list of the underlying protocols is fixed forever in all its instances? Having it in the form of identity would allow later augmenting of the list of possible values.

**Comment by sbarguil** [comment]
The proposed solution:

```
identity protocol-type {
      description
      "Base identity for Protocol Type.";
  }

  identity GRE {
    base protocol-type ;
    description
      "Transport based on GRE.";
  }

  identity LDP {
    base protocol-type ;
    description
      "Transport based on LDP.";
  }
  
  identity BGP {
    base protocol-type ;
    description
      "Transport based on BGP.";
  }

  identity SR {
    base protocol-type ;
    description
      "Transport based on SR.";
  }

  identity SR-TE {
    base protocol-type ;
    description
      "Transport based on SR.";
  }

  identity RSVP-TE {
    base protocol-type ;
    description
      "Transport based on SR.";
  }

  identity unknown {
    base protocol-type ;
    description
      "Transport based on SR.";
  }
```

```
           +--rw underlay-transport
           |  +--rw type*   identityref
```

**Comment by boucadair** [comment]
Thanks, Samier. 

* We need to add reference clauses, e.g., 

  identity gre {
    base protocol-type ;
    description
      "Transport based on Generic Routing Encapsulation (GRE).";
       reference
         "RFC 1701: Generic Routing Encapsulation (GRE)
          RFC 1702: Generic Routing Encapsulation over IPv4 networks
          RFC 7676: IPv6 Support for Generic Routing Encapsulation
                    (GRE)";
  }

* use lowercase for the identity label, e.g., s/LDP/ldp

* Update the description to reflect identity, e.g., fix the descriptions of sr-te, rsvp-te, ..

**Comment by oscargdd** [comment]
Descriptions and referefences still pending (lower case change was made)

**Comment by boucadair** [comment]
We will need to add all these references to the Informative References of the draft and call them in the description text.
