### ISSUE TITLE
Routing policy: just a name or a reference to leaf in a routing policy yang?

### ISSUE THREAD

**Issue by oscargdd** [IETF-OPSAWG-WG/l3nm#117]
Currently, routing policies are just plain strings. There is a yang module to store policies (ietf-routing-policies). In adition to a plain string, we could have either:

a) leafref pointing to the policy ietf-routing-policies module.
(drawback adds a depencency)
b) add type of policy (proprietary-policy, ietf-routing-policy) Then, if the type is ietf-routing-policy, the policy can be quieried in such module. Otherwise it is proprietary to the implementation

**Comment by boucadair** [comment]
But in both cases you have a dependency.

As the pointer of the policy will be local anyway, having a local id exposed in thei L3NM is sufficient, IMO. Any glue/mapping to proprietary-policy, ietf-routing-policy will be up to the controller.

**Comment by oscargdd** [comment]
WG decission was to maintain just a hook, no leafref
