### ISSUE TITLE
VRRP primary and backup group support or loadbalancing support

### ISSUE THREAD

**Issue by billwuqin** [IETF-OPSAWG-WG/l3nm#119]
The relationship between network accesss and VRRP is as follows:
        |     +--rw vpn-network-accesses
        |     |  +--rw vpn-network-access*
        |     |          [vpn-network-access-id]
        |     |     +--rw vpn-network-access-id      svc-id
        |     |     +--rw routing-protocols
        |     |        +--rw routing-protocol* [id]
        |     |           +--rw vrrp {rtg-vrrp}?
        |     |              +--rw address-family*
        |     |                      address-family
Suppose we have two network accesses, network access-1 connecting to PE1 and network-access-2, connecting to PE2, how do we represent two network-accesses are grouped together for load balancing, suppose we have two loadbalancing group, group 1, and group 2, PE1 is primary device in group 1 and backup device in group 2 while PE2 is the primary device in group 2 and backup device in group, who do we represent this?

Second example, suppose we have network-accesses, network-access-1 connecting to PE1, network-access-2 connecting to PE2 and network-access-3 connecting to PE3, we will group these three network-accesses as backup group, we hope based on priority value, to decide PE1 as primary device, PE2 and PE3 as backup device, how do we support this case?

**Comment by billwuqin** [comment]
#119 is related to #85 ,suggest to close #119.

**Comment by sbarguil** [comment]
The suggested proposal:

    container vrrp {
     when "derived-from-or-self(../type, 'l3vpn-ntw:vrrp')" {
      description
      "Only applies when protocol is VRRP.";
     }
     if-feature rtg-vrrp;
     leaf-list address-family {
      type address-family;
          min-elements "1";
         description
         "If VRRP is used on this site, this node
         contains a configured value.  This node contains
         at least one address family to be activated.";
     }
     leaf vrrp-group {
      type uint8 {
        range "1..255";
      }
      description "VRRP group number";
     }
     leaf backup-peer {
      type inet:ipv4-address;
      description "IP address of the peer";
     }
     leaf priority {
      type uint8;
      description "Local priority of the VRRP speaker";
     }
     leaf ping-reply {
      type boolean;
      description "Whether the VRRP speaker should answer to ping requests";
     }
     description
     "Configuration specific to VRRP routing.";
    }
