### ISSUE TITLE
IP connection: Simplify the address assignment strucure

### ISSUE THREAD

**Issue by boucadair** [IETF-OPSAWG-WG/l3nm#124]
I wonder whether we can delete "address-allocation-type" and go for this simplified structure (see the IPv4 example):
 
OLD:
=
              |     |  +--rw ipv4 {l3vpn-svc:ipv4}?
              |     |  |  +--rw address-allocation-type?
              |     |  |  |       identityref
              |     |  |  +--rw provider-dhcp
              |     |  |  |  +--rw provider-address?
              |     |  |  |  |       inet:ipv4-address
              |     |  |  |  +--rw prefix-length?
              |     |  |  |  |       uint8
              |     |  |  |  +--rw (address-assign)?
              |     |  |  |     +--:(number)
              |     |  |  |     |  +--rw number-of-dynamic-address?
              |     |  |  |     |          uint16
              |     |  |  |     +--:(explicit)
              |     |  |  |        +--rw customer-addresses
              |     |  |  |           +--rw address-group*
              |     |  |  |                   [group-id]
              |     |  |  |              +--rw group-id
              |     |  |  |              |       string
              |     |  |  |              +--rw start-address?
              |     |  |  |              |       inet:ipv4-address
              |     |  |  |              +--rw end-address?
              |     |  |  |                      inet:ipv4-address
              |     |  |  +--rw dhcp-relay
              |     |  |  |  +--rw provider-address?
              |     |  |  |  |       inet:ipv4-address
              |     |  |  |  +--rw prefix-length?           uint8
              |     |  |  |  +--rw customer-dhcp-servers
              |     |  |  |     +--rw server-ip-address*
              |     |  |  |             inet:ipv4-address
              |     |  |  +--rw static-addresses
              |     |  |     +--rw primary-address?   leafref
              |     |  |     +--rw address* [address-id]
              |     |  |        +--rw address-id          string
              |     |  |        +--rw provider-address?
              |     |  |        |       inet:ipv4-address
              |     |  |        +--rw customer-address?
              |     |  |        |       inet:ipv4-address
              |     |  |        +--rw prefix-length?      uint8

NEW:

                |     |  +--rw ipv4 {vpn-common:ipv4}?
                 |     |  |  +--rw (address-assign)?
                 |     |  |     +--:(provider-dhcp)
                 |     |  |     |  +--rw provider-address?                  inet:ipv4-address
                 |     |  |     |  +--rw prefix-length?                     uint8
                 |     |  |     |  +--rw (address-assign)?
                 |     |  |     |     +--:(number)
                 |     |  |     |     |  +--rw number-of-dynamic-address?   uint16
                 |     |  |     |     +--:(explicit)
                 |     |  |     |        +--rw customer-addresses
                 |     |  |     |           +--rw address-group* [group-id]
                 |     |  |     |              +--rw group-id         string
                 |     |  |     |              +--rw start-address?   inet:ipv4-address
                 |     |  |     |              +--rw end-address?     inet:ipv4-address
                 |     |  |     +--:(dhcp-relay)
                 |     |  |     |  +--rw provider-address?                  inet:ipv4-address
                 |     |  |     |  +--rw prefix-length?                     uint8
                 |     |  |     |  +--rw customer-dhcp-servers
                 |     |  |     |     +--rw server-ip-address*   inet:ipv4-address
                 |     |  |     +--:(static-address)
                 |     |  |        +--rw primary-address?                   
                 |     |  |        +--rw address* [address-id]
                 |     |  |           +--rw address-id          string
                 |     |  |           +--rw provider-address?   inet:ipv4-address
                 |     |  |           +--rw customer-address?   inet:ipv4-address
                 |     |  |           +--rw prefix-length?      uint8

**Comment by billwuqin** [comment]
Do we have a case where both static-address and provider-dhcp needs to be configured? If the answer is no, I think we could take your proposal.

**Comment by sbarguil** [comment]
in our case we dont have it. Just one or the other, I like the proposal, the simpler the better!

**Comment by billwuqin** [comment]
Then agree to switch to the case choice.

**Comment by billwuqin** [comment]
If we change to choice case, each parameter name in the case should be unique, therefore provider-address in provider-dhcp case and provider-address in dhcp-relay case will conflict.

**Comment by boucadair** [comment]
> 
> 
> If we change to choice case, each parameter name in the case should be unique, therefore provider-address in provider-dhcp case and provider-address in dhcp-relay case will conflict.

Agree. This should be fixed if we go that path.

**Comment by boucadair** [comment]
The new tree is as follows: 

                 |     +--rw ip-connection
                 |     |  +--rw ipv4 {vpn-common:ipv4}?
                 |     |  |  +--rw address-allocation-type?
                 |     |  |  |       identityref
                 |     |  |  +--rw (allocation-type)?
                 |     |  |     +--:(provider-dhcp)
                 |     |  |     |  +--rw provider-address?
                 |     |  |     |  |       inet:ipv4-address
                 |     |  |     |  +--rw prefix-length?
                 |     |  |     |  |       uint8
                 |     |  |     |  +--rw (address-assign)?
                 |     |  |     |     +--:(number)
                 |     |  |     |     |  +--rw number-of-dynamic-address?
                 |     |  |     |     |          uint16
                 |     |  |     |     +--:(explicit)
                 |     |  |     |        +--rw customer-addresses
                 |     |  |     |           +--rw address-group*
                 |     |  |     |                   [group-id]
                 |     |  |     |              +--rw group-id
                 |     |  |     |              |       string
                 |     |  |     |              +--rw start-address?
                 |     |  |     |              |       inet:ipv4-address
                 |     |  |     |              +--rw end-address?
                 |     |  |     |                      inet:ipv4-address
                 |     |  |     +--:(dhcp-relay)
                 |     |  |     |  +--rw dr-provider-address?
                 |     |  |     |  |       inet:ipv4-address
                 |     |  |     |  +--rw dr-prefix-length?
                 |     |  |     |  |       uint8
                 |     |  |     |  +--rw customer-dhcp-servers
                 |     |  |     |     +--rw server-ip-address*
                 |     |  |     |             inet:ipv4-address
                 |     |  |     +--:(static-addresses)
                 |     |  |        +--rw primary-address?
                 |     |  |        |       -> ../address/address-id
                 |     |  |        +--rw address* [address-id]
                 |     |  |           +--rw address-id
                 |     |  |           |       string
                 |     |  |           +--rw s-provider-address?
                 |     |  |           |       inet:ipv4-address
                 |     |  |           +--rw s-customer-address?
                 |     |  |           |       inet:ipv4-address
                 |     |  |           +--rw s-prefix-length?
                 |     |  |                   uint8
                 |     |  +--rw ipv6 {vpn-common:ipv6}?
                 |     |  |  +--rw address-allocation-type?
                 |     |  |  |       identityref
                 |     |  |  +--rw (allocation-type)?
                 |     |  |     +--:(provider-dhcp)
                 |     |  |     |  +--rw (provider-dhcp)?
                 |     |  |     |     +--:(provider-address)
                 |     |  |     |     |  +--rw provider-address?
                 |     |  |     |     |          inet:ipv6-address
                 |     |  |     |     +--:(prefix-length)
                 |     |  |     |     |  +--rw prefix-length?
                 |     |  |     |     |          uint8
                 |     |  |     |     +--:(address-assign)
                 |     |  |     |        +--rw (address-assign)?
                 |     |  |     |           +--:(number)
                 |     |  |     |           |  +--rw number-of-dynamic-address?
                 |     |  |     |           |          uint16
                 |     |  |     |           +--:(explicit)
                 |     |  |     |              +--rw customer-addresses
                 |     |  |     |                 +--rw address-group*
                 |     |  |     |                         [group-id]
                 |     |  |     |                    +--rw group-id
                 |     |  |     |                    |       string
                 |     |  |     |                    +--rw start-address?
                 |     |  |     |                    |       inet:ipv6-address
                 |     |  |     |                    +--rw end-address?
                 |     |  |     |                            inet:ipv6-address
                 |     |  |     +--:(dhcp-relay)
                 |     |  |     |  +--rw dr-provider-address?
                 |     |  |     |  |       inet:ipv6-address
                 |     |  |     |  +--rw dr-prefix-length?
                 |     |  |     |  |       uint8
                 |     |  |     |  +--rw customer-dhcp-servers
                 |     |  |     |     +--rw server-ip-address*
                 |     |  |     |             inet:ipv6-address
                 |     |  |     +--:(static-addresses)
                 |     |  |        +--rw s-primary-address?
                 |     |  |        |       -> ../s-address/address-id
                 |     |  |        +--rw s-address* [address-id]
                 |     |  |           +--rw address-id
                 |     |  |           |       string
                 |     |  |           +--rw provider-address?
                 |     |  |           |       inet:ipv6-address
                 |     |  |           +--rw customer-address?
                 |     |  |           |       inet:ipv6-address
                 |     |  |           +--rw prefix-length?      uint8
