### ISSUE TITLE
Initial set of comments for ietf-vpn-common

### ISSUE THREAD

**Issue by italobusi** [IETF-OPSAWG-WG/l3nm#131]
I have started to review the ietf-vpn-common.yang and got some comments

I have also started to check if there are groupings that can be defined within the common model

**Comment by italobusi** [comment]
Comments to the current YANG module are embedded as "IB Comment" within this file:

**Comment by italobusi** [comment]
I think we can define a common grouping for the service instances:

L3SM:

       |     +--rw vpn-id                  svc-id
       |     +--rw customer-name?          string
       |     +--rw vpn-service-topology?   identityref

L2SM:

     |     +--rw vpn-id                      svc-id
     |     +--rw vpn-svc-type?               identityref
     |     +--rw customer-name?              string
     |     +--rw svc-topo?                   identityref

L3NM:

       +--rw vpn-id                  l3vpn-svc:svc-id
       +--rw l3sm-vpn-id?            l3vpn-svc:svc-id
       +--rw customer-name?          string
       +--rw vpn-service-topology?   identityref
       +--rw description?            string

L2NM:
              +--rw vpn-id                      svc-id
              +--rw vpn-service-type?           identityref
              +--rw customer-name?              string
              +--rw svc-topo?                   identityref

Common:

       +--rw vpn-id                  svc-id
       +--rw vpn-name                string
       +--rw vpn-description         string
       +--rw customer-name?          string
       +--rw vpn-service-topology?   identityref

L2NM/L2SM common:

       +--rw vpn-id                  svc-id         // from common
       +--rw vpn-name                string         // from common
       +--rw vpn-description         string         // from common
       +--rw customer-name?          string         // from common
       +--rw vpn-service-topology?   identityref    // from common
       +--rw vpn-svc-type?           identityref

Issue: L2SM defines svc-topo instead of vpn-service-topology ...
       Moreover, vpn-service-topology might not be applicable to L1CSM

Possible solution:

Common:

       +--rw vpn-id                  svc-id
       +--rw vpn-name?               string
       +--rw vpn-description?        string
       +--rw customer-name?          string

L3NM/L3SM common:
       +--rw vpn-id                  svc-id         // from common
       +--rw vpn-name                string         // from common
       +--rw vpn-description         string         // from common
       +--rw customer-name?          string         // from common
       +--rw vpn-service-topology?   identityref

L2NM/L2SM common:

       +--rw vpn-id                  svc-id         // from common
       +--rw vpn-name                string         // from common
       +--rw vpn-description         string         // from common
       +--rw customer-name?          string         // from common
       +--rw svc-topo?               identityref
       +--rw vpn-svc-type?           identityref

**Comment by italobusi** [comment]
The l2cp-grouping seems in common between L2SM and L2NM and could be moved into this common model

**Comment by boucadair** [comment]
> 
> 
> Comments to the current YANG module are embedded as "IB Comment" within this file:
> 
> [ietf-vpn-common-ib-2020-06-26.yang.txt](https://github.com/IETF-OPSAWG-WG/l3nm/files/4839222/ietf-vpn-common-ib-2020-06-26.yang.txt)

Thanks Italo for the comments. Below some clarifications to your comments 

=
  IB comment:
  
    Why "for example"? Are there other uses for this type?
    
    In current drafts, the type is called svd-id which looks more generic than vpn-id.
    
    What about the following description:
    
    "A service (e.g., VPN) identifier."
=

This is a fair comment. The intent was to make a distinct between the network-centric of the service (e.g., L3NM) and a "pure" service identifier as in L3SM.

OLD:
      +--rw vpn-id                  l3vpn-svc:svc-id
      +--rw l3sm-vpn-id?            l3vpn-svc:svc-id 
NEW:
      +--rw vpn-id                  vpn-common:svc-id
      +--rw l3sm-vpn-id?        vpn-common:svc-id

I'm OK to remove "for example" if you think this is confusing

**Comment by boucadair** [comment]
> 
> 
> The l2cp-grouping seems in common between L2SM and L2NM and could be moved into this common model

=
  IB comment:
  
    In other models the status UNKNOWN is not defined.
    
    My understanding is that if the operational-status is optional, it is possible not to report it when unknown.
    
=

This is status can be reported if the controller fails to retrieve the status of the service. It is OK to have it a value to be reported.

**Comment by boucadair** [comment]
> 
> 
> Comments to the current YANG module are embedded as "IB Comment" within this file:
> 
> [ietf-vpn-common-ib-2020-06-26.yang.txt](https://github.com/IETF-OPSAWG-WG/l3nm/files/4839222/ietf-vpn-common-ib-2020-06-26.yang.txt)

=
  identity administrative-state-pre-deployment {
    base administrative-status;
    description
      "Administrative status is pre-deployment phase.";
  }

 
  What does it mean pre-deployment?
=

This is the last stage before actual activation of the service. The configuration is up and running but with limited access. This is more than testing.

**Comment by boucadair** [comment]
> 
> 
> Comments to the current YANG module are embedded as "IB Comment" within this file:
> 
> [ietf-vpn-common-ib-2020-06-26.yang.txt](https://github.com/IETF-OPSAWG-WG/l3nm/files/4839222/ietf-vpn-common-ib-2020-06-26.yang.txt)

=
  identity unknown {
    base protocol-type;
    description
      "Not known at this stage.";
  }

  IB comment:
  
    Do we need unknown identity? In this case, the protocol type can be omitted.
=

I suggest to maintain it. This value can be used for reporting purposes.

**Comment by boucadair** [comment]
> 
> 
> Comments to the current YANG module are embedded as "IB Comment" within this file:
> 
> [ietf-vpn-common-ib-2020-06-26.yang.txt](https://github.com/IETF-OPSAWG-WG/l3nm/files/4839222/ietf-vpn-common-ib-2020-06-26.yang.txt)

=
  IB Comment:
  
    The naming is not intuitive
    
    What about:
      c/status-timestamp/operational-status/
      c/leaf status/leaf operational-status/leaf
      c/timestamp/last-updated-time/
    
    In client-signal we have got a requirement to track also the creation-time.
    
    In client-signal we have also got a requirement to report the provisioning-state (e.g., setup in progress).
    
    I think these requirements could be also applicable to L2NM and L3NM.
=

The grouping may be called for both admin and operational purposes. I would avoid adding "operational" into the name. This grouping is called under "container oper-status" for example.

OK with "s/timestamp/last-updated-time/"

**Comment by boucadair** [comment]
>    +--rw vpn-id                  svc-id         // from common
>    +--rw vpn-name                string         // from common
>    +--rw vpn-description         string         // from common
>    +--rw customer-name?          string         // from common

Looks good to me. Thanks

**Comment by italobusi** [comment]
> If we remove "for example", we will need to update these parts as well.
> 
> It is better to have distinct types of vpn service, access, and site, though

The clarification is quite useful.

What about the following proposal:

```
  typedef svc-id {
    type string;
    description
      "Defines a service element (e.g., vpn, network-access) identifier.";
  }
```

**Comment by boucadair** [comment]
> 
> 
> > If we remove "for example", we will need to update these parts as well.
> > It is better to have distinct types of vpn service, access, and site, though
> 
> The clarification is quite useful.
> 
> What about the following proposal:
> 
> ```
>   typedef svc-id {
>     type string;
>     description
>       "Defines a service element (e.g., vpn, network-access) identifier.";
>   }
> ```

Works for me. See #177

**Comment by boucadair** [comment]
The outcome of this issue was impemented in the common draft.
