### ISSUE TITLE
Review vpn_profiles

### ISSUE THREAD

**Issue by oscargdd** [IETF-OPSAWG-WG/l3nm#18]
vpn_profiles were inherited from L3SM. We need to review this part of the yang model

**Comment by oscargdd** [comment]
VPN profiles Will be kept. A description in section 6.2 Will be added

**Comment by boucadair** [comment]
@oscargdd: this one is also to be closed. Thanks.

**Comment by oscargdd** [comment]
Review done and all the profiles in the common module.
