### ISSUE TITLE
Update -04 draft text

### ISSUE THREAD

**Issue by oscargdd** [IETF-OPSAWG-WG/l3nm#184]
Update -04 draft text

**Comment by boucadair** [comment]
Check at: https://github.com/IETF-OPSAWG-WG/l3nm/blob/master/I-D-L3NM/draft-ietf-opsawg-l3sm-l3nm-04.txt

The full set of changes can be tracked at: https://github.com/IETF-OPSAWG-WG/l3nm/commits/master/I-D-L3NM

**Comment by oscargdd** [comment]
-04 version uploaded and published
