### ISSUE TITLE
Use documentation IPv4 addresses in the examples + Add IPv6 Examples

### ISSUE THREAD

**Issue by boucadair** [IETF-OPSAWG-WG/l3nm#187]
See RFC 6890

**Comment by oscargdd** [comment]
Update expamples in the appendix with both IPv4 and IPv6. There are already examples available to use as a base.

**Comment by boucadair** [comment]
Fixed in https://github.com/IETF-OPSAWG-WG/l3nm/commit/e2eaae9a9036d19c26330fbaba916047e4968e53
