### ISSUE TITLE
Decide whether we need to cover access to CSP (RFC8299)

### ISSUE THREAD

**Issue by boucadair** [IETF-OPSAWG-WG/l3nm#189]
RFC8299 includes the following: 

       |     +--rw cloud-accesses {cloud-access}?
       |     |  +--rw cloud-access* [cloud-identifier]
       |     |     +--rw cloud-identifier       leafref
       |     |     +--rw (list-flavor)?
       |     |     |  +--:(permit-any)
       |     |     |  |  +--rw permit-any?            empty
       |     |     |  +--:(deny-any-except)
       |     |     |  |  +--rw permit-site*
       |     |     |  |          -> /l3vpn-svc/sites/site/site-id
       |     |     |  +--:(permit-any-except)
       |     |     |     +--rw deny-site*
       |     |     |             -> /l3vpn-svc/sites/site/site-id
       |     |     +--rw address-translation
       |     |        +--rw nat44
       |     |           +--rw enabled?                  boolean
       |     |           +--rw nat44-customer-address?
       |     |                   inet:ipv4-address

**Comment by oscargdd** [comment]
The service orchestrator (that receives and processes L3SM requests) will translate the cloud/internet access requirements into specific CE-PE configurations (that are part of L3NM). Need to check use cases that include e.g. address translations.

We have a cloud identifier. Need to check if it is needed.

**Comment by boucadair** [comment]
If we include cloud access, we need to include in general access to Internet. Although there are many options to offer those, one typical scenario is to NAT the traffic + grafting to an external realm is managed outside the PE (still some tweaking is needed at the PE). 

rfc8512#section-2.10 defines how to bind a NAT instance to VRF. We don't need to overload the module with these aspects. 

I'm afraid that cloud-identifier is not useful at the L3NM level. Instead, we may consider an "external-connectivity" node that we can position at the "vpn-service" level to ease gluing L3NM with companion configuration that can be on the external interface of the PE + other nodes in the network to offer that external connectivity.

**Comment by oscargdd** [comment]
add profiles for external connections (which can include the cloud, the nat...)

**Comment by oscargdd** [comment]
it can be called at service or network access level. Suggestions? Please comment in the thread :-)

**Comment by boucadair** [comment]
The common module is updated with external-connectivity: https://github.com/IETF-OPSAWG-WG/l3nm/commit/4658de7073f5c7bac6328400ad33de70ad213870

**Comment by oscargdd** [comment]
Explanatory text already provided. Agreed to maintain it as a profile at vpn service level as the implementations are today diverse.
