### ISSUE TITLE
Clarify Multicast

### ISSUE THREAD

**Issue by oscargdd** [IETF-OPSAWG-WG/l3nm#19]
Currently multicast is a top-level structure. However, multicast applies to a particular vpn_service.

**Comment by oscargdd** [comment]
Stephane is checking the multicast

**Comment by sli35** [comment]
Multicast is attached correctly to a particular vpn-service (not vpn-node)
Then each site can have its own multicast parameters.

**Comment by oscargdd** [comment]
The muticast container as you mention is attached to vpn-service. @sli35 you mention "Then each site can have its own multicast parameters", but if the multicast configuration is for the whole service, the configuration is not per customer site. Can you clarify?

**Comment by sli35** [comment]
The top-level container (under vpn-services) describe the overall multicast setup, like RPs...
Under each site you have some parameters like, is the site a receiver or source site

**Comment by sbarguil** [comment]
Multicast params were included in the last version

**Comment by oscargdd** [comment]
Vodafone (Luis and Manolo) to review the multicast

**Comment by luciaob** [comment]
After being working with a real multicast scenario, we have realized that multicast parameters should be configured at vpn-node level.
For example: each node have a different local-address value within msdp feature.

**Comment by oscargdd** [comment]
Multicast has been thoroughly reviewed and improved with a real multicast scenario. Pull request https://github.com/luciaob/l3nm/commit/dca0590845a79b942982175f95e82e20ec6e144e
