### ISSUE TITLE
Luis Angel's Comment: Multipoint “vpn-network-access-type”

### ISSUE THREAD

**Issue by boucadair** [IETF-OPSAWG-WG/l3nm#190]
The definition of Multipoint “vpn-network-access-type” is exactly the same as the previous Point-to-point one, I don’t have an alternative wording to propose, please the editor of this chapter to check which is the difference and make it clearer. Otherwise I do not see the rationale for the alternatives to be explained.

**Comment by lmunozm** [comment]
Test have been fixed for the upload as follows:

Multipoint: This option represents a broadcast connection between
       end-points.  It implies the controller must keep the
      association between a logical or physical interface on the device
      with the 'id' of the 'vpn-network-access'.

**Comment by oscargdd** [comment]
closed per luis angel comments.
