### ISSUE TITLE
additional static routes attributes 

### ISSUE THREAD

**Issue by segevere** [IETF-OPSAWG-WG/l3nm#191]
Missing 
:
1) BFD - enable/disable
2) metric -uint32
3) preference - uint32
4) special NH such as blackhole

all needed for IPv4 and IPv6 as well.

**Comment by oscargdd** [comment]
BFD Part: Now it is only at interface level. It could be added at static route level. Include the container in the routing protocols.

**Comment by oscargdd** [comment]
We have metic at IS-IS and Opsf level, but not at static route level. Can be added.

**Comment by oscargdd** [comment]
preference is at OSPF level. Can be added also

**Comment by oscargdd** [comment]
Erez, please provide more information of the blackhole. Provide reference

**Comment by sbarguil** [comment]
@segevere Can you please check the #199 to see if that fit the requirement?
