### ISSUE TITLE
Review PE-CE security section

### ISSUE THREAD

**Issue by oscargdd** [IETF-OPSAWG-WG/l3nm#192]
Review PE-CE security section

- Is it L3 specific? can it go to the common module?

- Is current content enough to cover PE-CE authentication use cases?

**Comment by boucadair** [comment]
See the updates in https://github.com/IETF-OPSAWG-WG/l3nm/commit/aae9153e01a900d4dd4d25c80fde5282c9453e85 

I suggest to leave these nodes in the L3NM.
