### ISSUE TITLE
error in l3nm: grouping "vpn-node-group" not found in module "ietf-vpn-common"

### ISSUE THREAD

**Issue by oscargdd** [IETF-OPSAWG-WG/l3nm#193]
pyang -f tree --ietf ietf-l3vpn-ntw.yang
ietf-l3vpn-ntw.yang:303: error: grouping "vpn-node-group" not found in module "ietf-vpn-common"

**Comment by boucadair** [comment]
@oscargdd , this should be changed to "vpn-common:group".
