### ISSUE TITLE
service type and signaling option type

### ISSUE THREAD

**Issue by boucadair** [IETF-OPSAWG-WG/l3nm#195]
Clean up service type and signaling option type and avoid content overlapping

**Comment by oscargdd** [comment]
Clean up first. Second add explantation. Third, examples with possible combinations of service-type, signaling type and underlay-transport.

**Comment by oscargdd** [comment]
Find better name (or  better explantation) for signaling type. The signaling type focuses on control plane.

**Comment by oscargdd** [comment]
In L3NM we have now vpn_type ¿is it needed?

**Comment by billwuqin** [comment]
See https://github.com/IETF-OPSAWG-WG/l3nm/pull/200
The VPN type has been linked to vpn signaling type
"
        leaf vpn-type {
          type identityref {
            base vpn-common:vpn-signaling-type;
          }
"

**Comment by boucadair** [comment]
covered in https://github.com/IETF-OPSAWG-WG/l3nm/commit/553b657143305a944fd7c303262d8ca0eabe98a6
