### ISSUE TITLE
Service feasibility only request?

### ISSUE THREAD

**Issue by sbarguil** [IETF-OPSAWG-WG/l3nm#196]
Should we include a Boolean to indicate that the request is done to validate service feasibility.

**Comment by oscargdd** [comment]
One option could be to add a new opertational discussion

**Comment by oscargdd** [comment]
Opinions: What adds more value seems to be related to the underlay transport.

**Comment by boucadair** [comment]
> Opinions: What adds more value seems to be related to the underlay transport.

As we don't expose capabilities (including underlying transport), I suggest we discard this.
