### ISSUE TITLE
Service Mapping: Association between services

### ISSUE THREAD

**Issue by sbarguil** [IETF-OPSAWG-WG/l3nm#211]
To Add a pointer to relate l3/l2 services.

**Comment by boucadair** [comment]
For this one, I'm afraid that this is redundant with with the resolution made in #212. 

Disjointness between two services can be implemented by grafting VPN services to distinct transport-instance-ids that are build to satisfy the disjointness constraint (see for example, draft-ietf-teas-actn-vn-yang, draft-ietf-teas-enhanced-vpn, or the isolation discussed in draft-ietf-teas-ietf-network-slice-definition).

I suggest we discard this one.

**Comment by oscargdd** [comment]
The information in the new instance-id can be used to perform disjointness. Let's close it as med suggests to avoid overloading the model.
