### ISSUE TITLE
TE Service Mapping: Slice Identifier

### ISSUE THREAD

**Issue by sbarguil** [IETF-OPSAWG-WG/l3nm#212]
To put in the common model the pointers to the slice (`slice-id`). So the slice can be included in the L2 and L3nm.

**Comment by julianL999** [comment]
Would be good if the slice-id could be a string, then the user can put any form of information there to identify the slice.

**Comment by boucadair** [comment]
> 
> 
> Would be good if the slice-id could be a string, then the user can put any form of information there to identify the slice.

Agree. 

We need something generic to accommodate the various concepts (VPN+ (draft-ietf-teas-enhanced-vpn), ACTN, slicing, ..). Also, we need to avoid mixing "abstract" things vs. concrete implementation. 

Please check the proposal at https://github.com/IETF-OPSAWG-WG/l3nm/commit/e9fa0fbc5ce3216a2f7790c7ea7ecf89d3dda743 and let me know if you are happy with it.

**Comment by julianL999** [comment]
Yes, that looks great. (Spotted a typo: transport-intance-id -> transport-instance-id)

**Comment by boucadair** [comment]
Thanks, Julian. 

The nit was fixed here https://github.com/IETF-OPSAWG-WG/l3nm/commit/8fd74a7a41d394c08d20072b330915d8df443bfd

**Comment by sbarguil** [comment]
@boucadair If an OSS system requires a particular network slice, the Network Slice Controller (SDN controller) must know what signaling protocol is deployed in the network to deliver the service (at least for READ purposes). If we model this as a choice, the controller can't report both attributes. 

IMO both attributes can be useful for troubleshooting in case of service failure.  What do you think?

**Comment by boucadair** [comment]
> Network Slice Controller

Samier, the network slice controller will use whatever available slice module to retrieve the underlying capabilities. It won't use LxNM for that purpose. 

Thats's said, the LxNM can be used the actual underlay transport that is put into effect for that given VPN service. It is a choice on purpose as the technical implementation of a slice will details which technologies are tweaked to meet the SLOs. Having both will be redundant in our module.

**Comment by sbarguil** [comment]
Understod! 

I know that this is something we have not discussed. But we were thinking in the following scenario: 

![image](https://user-images.githubusercontent.com/13772485/107538008-84f4d580-6b91-11eb-8c7c-2f855f608fce.png)

1. Request the Network Slice to the Hierarchical controller or Network Orchestrator. 
2. The Orchestrator must translate this request to the controller using the L3NM. 

In this scenario, it would be useful not only to store the slice-id but also the underlay preference selected by the orchestrator. 

Do you see this scenario feasible? 

The slices yang modules available on the IETF are less detailed that the L3nm so we were considering to re-use it. 
The orchestrator can really abstract the complexity and expose a high level module.

**Comment by boucadair** [comment]
LxNM can be used to realize a network slice. That makes sense to me. 

That one is doable if we generalize the reference to the parent service request as follows:

OLD
```
        +--rw vpn-services
           +--rw vpn-service* [vpn-id]
              ...
              +--rw l3sm-vpn-id?            vpn-common:vpn-id
```

NEW:
```
        +--rw vpn-services
           +--rw vpn-service* [vpn-id]
              ...
              +--rw service-id?            vpn-common:vpn-id
```

l3sm-vpn-id can be cited as an example of the parent service request, but not the only one. 

The preferred underlay transport can then be reported use the "protocol" case.

**Comment by sbarguil** [comment]
I think this reference generalization is perfect!

**Comment by boucadair** [comment]
> 
> 
> I think this reference generalization is perfect!

Deal!

Please see https://github.com/IETF-OPSAWG-WG/l3nm/commit/77e2f849f65bd65f91706aa6ec98a38868d05fbb.

**Comment by oscargdd** [comment]
Suggestion is to add in the "abstract" containter under underlay a type. Now, a base identity can be defined, and then, subsequent augmentations can define this types (for example, the "transport slice", "ACTN Virtual network", "VPN+", etc, as they are standardized.
