### ISSUE TITLE
Maximum Routes (Prefixes) Generalization

### ISSUE THREAD

**Issue by sbarguil** [IETF-OPSAWG-WG/l3nm#213]
The current model support limit the maximum routes number based on the Address Family:

![image](https://user-images.githubusercontent.com/13772485/107616488-2b85b880-6c1c-11eb-8774-c22b1af8a2f9.png)

This limitation can be extended to not only select the address family but also for protocol where this limitation is applied:

```
                 +--rw maximum-routes
                 |  +--rw selector* [address-family protocol]
                 |  |  +--rw address-family    identityref
                 |  |  +--rw protocol          identityref
                 |  |  +--rw maximum-routes?   uint32
```

Several protocols may have different upper limits.

**Comment by boucadair** [comment]
Sounds good but if one wants to apply the limit to any (or all) protocol, it has to do it one by one (as the protocol is a key).

One way to proceed is to define an "any-protocol" identity. Only one limit entry per AF will be needed in such case.

**Comment by oscargdd** [comment]
ok, modifications looks good. The issue will be closed once the PR is merged
