### ISSUE TITLE
IGMP Support as Routing Protocol

### ISSUE THREAD

**Issue by sbarguil** [IETF-OPSAWG-WG/l3nm#215]
Include IGMP as a routing protocol for the CE-PE connectivity.

**Comment by boucadair** [comment]
I would define a new identity for IGMP and MLD to avoid mixing mutlicast subscription with routing.

**Comment by boucadair** [comment]
Samier, what is the role of "subscription-channel" at the node level?

Also, please check  https://github.com/IETF-OPSAWG-WG/l3nm/commit/da3ef4dee0b75d5ba15d943a9786ea8625c19849 to see the initial nodes I added at the network access level. Do we need to add max-group-sources? filter the sources? filter the groups?

**Comment by sbarguil** [comment]
`subscription-channel`refers to the multicast-ip-address to create the static group association. For example, 

```
set protocols igmp interface lt-2/0/0.2180 static group 239.0.0.40 group-count 1
set protocols igmp interface lt-2/0/0.2180 static group 239.0.0.41 group-count 1
set protocols igmp interface lt-2/0/0.2180 static group 239.0.0.42 group-count 1
set protocols igmp interface lt-2/0/0.2180 static group 239.0.0.43 group-count 1
set protocols igmp interface lt-2/0/0.2180 static group 239.0.0.44 group-count 1
````

The configuration we have been using do not have max group limitation, but it has filters to allow certain addresses to be visible or restricted in certain locations but I don't see this very standard.

**Comment by boucadair** [comment]
Thanks, Samier. I suggest to change the name to include "static" in the name and to make clear this is about a multicast group. 

For the policies, and given that we control unicast routes, I'd like we provide some minimal control at the L3NM for multicast. In order to ease correlation with RFC8652, we can define the following at the network access level for both IGMP and MLD:

                +--rw max-groups?                   uint32
                +--rw max-group-sources?            uint32

**Comment by sbarguil** [comment]
I thinks both suggestions are really usefull. Do you want that I make the PR?

**Comment by boucadair** [comment]
> 
> 
> I thinks both suggestions are really useful. Do you want that I make the PR?

Yes, please. Thanks.
