### ISSUE TITLE
L3NM: vrf loopback address and associated port-id at vpn node level

### ISSUE THREAD

**Issue by julianL999** [IETF-OPSAWG-WG/l3nm#221]
It would be very valuable for the L3NM to have a place for the VRF loopback address and associated "port-id" (which would just be a string, to accommodate different vendors' representations e.g. "Loopback1" or "lo0.1"). This would be at the vpn-node level. (The model currently allows IP addresses and associated port-id to be configured for PE-CE links, but this is at the wrong level of the hierarchy for the loopback address)

**Comment by oscargdd** [comment]
The model has the following procedure to add a loopack interface to a VRF:

* Create a new vpn-network access of type "loopack". This type indicates that it is NOT a CE-PE connection.
* Provide the IP address for the loopback
* Optionally, a port-id, which is currently a string, can be used to include the representation.

We can add a clarifying text in the VPN network acccess section.

**Comment by julianL999** [comment]
> The model has the following procedure to add a loopack interface to a VRF:
> 
>     * Create a new vpn-network access of type "loopack". This type indicates that it is NOT a CE-PE connection.
> 
>     * Provide the IP address for the loopback
> 
>     * Optionally, a port-id, which is currently a string, can be used to include the representation.
> 
> 
> We can add a clarifying text in the VPN network acccess section.

Yes, clarifying text would be welcome

**Comment by boucadair** [comment]
An example was included in the published -06
