### ISSUE TITLE
L3NM: support qos-custom as per RFC8299

### ISSUE THREAD

**Issue by julianL999** [IETF-OPSAWG-WG/l3nm#223]
It would be very valuable to support qos-custom, as per RFC8299, as some operators use this type of qos scheme.

**Comment by boucadair** [comment]
Hi Julian, 

We used to have this issue, but we closed it for reasons that you can see at https://github.com/IETF-OPSAWG-WG/l3nm/issues/53 

Thank you.

**Comment by julianL999** [comment]
> Hi Julian,
> 
> We used to have this issue, but we closed it for reasons that you can see at #53
> 
> Thank you.

Hi Med

The issue is that without Custom QoS, it is not possible to state a rate-limit per class, which some operators offer e.g. 

EF = 10 Mbps
AF = 25 Mbps
BE = 65 Mbps

**Comment by boucadair** [comment]
Thanks for clarifying. 

The concern we initialy had was with the bounds that are expressed in the custom QoS.

Rate-limiting is a valid case, but it does not to be put in the same level as other custom QoS service data nodes in RFC8299. 

I suggest to add a rate-limit data node directly to the QoS classification. The tree change will be as follows:

OLD:
```                ...
                  +--rw qos {vpn-common:qos}?
                  |  +--rw qos-classification-policy
                  |  |  +--rw rule* [id]
                  |  |     +--rw id             string
                  |  |     +--rw (match-type)?
                  |  |     |  +--:(match-flow)
                  |  |     |  |  +--rw (l3)?
                  |  |     |  |  |  +--:(ipv4)
                  |  |     |  |  |  |  ...
                  |  |     |  |  |  +--:(ipv6)
                  |  |     |  |  |     ...
                  |  |     |  |  +--rw (l4)?
                  |  |     |  |        ...
                  |  |     |  +--:(match-application)
                  |  |     |     +--rw match-application?
                  |  |     |             identityref
                  |  |     +--rw target-class-id?
                  |  |             string
                  ...
```
NEW:
```
                          +--rw qos {vpn-common:qos}?
                          |  +--rw qos-classification-policy
                          |  |  +--rw rule* [id]
                          |  |     +--rw id                         string
                          |  |     +--rw (match-type)?
                          |  |     |  +--:(match-flow)
                          |  |     |  |  +--rw (l3)?
                          |  |     |  |  |  +--:(ipv4)
                          |  |     |  |  |  |  ...
                          |  |     |  |  |  +--:(ipv6)
                          |  |     |  |  |     ...
                          |  |     |  |  +--rw (l4)?
                          |  |     |  |     ...
                          |  |     |  +--:(match-application)
                          |  |     |     +--rw match-application?   identityref
                          |  |     +--rw target-class-id?           string {qos}?
                          |  |     +--rw rate-limit?                decimal64
```

the change will in the common module by adding this new leaf under the qos-classification-policy grouping:

```
               leaf rate-limit {
                 type decimal64 {
                   fraction-digits 2;
                 }
                 units "bytes per second";
                 description
                   "Specifies whether/how to rate-limit the traffic
                    matching this rule.";
               }
```
Would that be OK with you?

**Comment by julianL999** [comment]
> Thanks for clarifying.
> 
> The concern we initialy had was with the bounds that are expressed in the custom QoS.
> 
> Rate-limiting is a valid case, but it does not to be put in the same level as other custom QoS service data nodes in RFC8299.
> 
> I suggest to add a rate-limit data node directly to the QoS classification. The tree change will be as follows:
> 
> OLD:
> 
> ```
>                   +--rw qos {vpn-common:qos}?
>                   |  +--rw qos-classification-policy
>                   |  |  +--rw rule* [id]
>                   |  |     +--rw id             string
>                   |  |     +--rw (match-type)?
>                   |  |     |  +--:(match-flow)
>                   |  |     |  |  +--rw (l3)?
>                   |  |     |  |  |  +--:(ipv4)
>                   |  |     |  |  |  |  ...
>                   |  |     |  |  |  +--:(ipv6)
>                   |  |     |  |  |     ...
>                   |  |     |  |  +--rw (l4)?
>                   |  |     |  |        ...
>                   |  |     |  +--:(match-application)
>                   |  |     |     +--rw match-application?
>                   |  |     |             identityref
>                   |  |     +--rw target-class-id?
>                   |  |             string
>                   ...
> ```
> 
> NEW:
> 
> ```
>                           +--rw qos {vpn-common:qos}?
>                           |  +--rw qos-classification-policy
>                           |  |  +--rw rule* [id]
>                           |  |     +--rw id                         string
>                           |  |     +--rw (match-type)?
>                           |  |     |  +--:(match-flow)
>                           |  |     |  |  +--rw (l3)?
>                           |  |     |  |  |  +--:(ipv4)
>                           |  |     |  |  |  |  ...
>                           |  |     |  |  |  +--:(ipv6)
>                           |  |     |  |  |     ...
>                           |  |     |  |  +--rw (l4)?
>                           |  |     |  |     ...
>                           |  |     |  +--:(match-application)
>                           |  |     |     +--rw match-application?   identityref
>                           |  |     +--rw target-class-id?           string {qos}?
>                           |  |     +--rw rate-limit?                decimal64
> ```
> 
> the change will in the common module by adding this new leaf under the qos-classification-policy grouping:
> 
> ```
>                leaf rate-limit {
>                  type decimal64 {
>                    fraction-digits 2;
>                  }
>                  units "bytes per second";
>                  description
>                    "Specifies whether/how to rate-limit the traffic
>                     matching this rule.";
>                }
> ```
> 
> Would that be OK with you?

It seems a pity to have a different implementation to RFC8299. It would be far preferable to have it consistent with RFC8299, as it fulfills the requirements efficiently. In the example in the RFC, the meaning of REAL_TIME, DATA1, DATA2 classes are already known to the operator and the customer (in the sense of what DSCP(s) etc map onto each class), so there is no need to state them in service order, the customer simply says what the rate is for each. (I just realise my example in my original post on this thread was wrong, I should have expressed it as percentages rather than absolute rates in bps).

**Comment by julianL999** [comment]
> > It seems a pity to have a different implementation to RFC8299. It would be far preferable to have it consistent with RFC8299, as it fulfills the requirements efficiently. In the example in the RFC, the meaning of REAL_TIME, DATA1, DATA2 classes are already known to the operator and the customer (in the sense of what DSCP(s) etc map onto each class), so there is no need to state them in service order, the customer simply says what the rate is for each.
> 
> That makes sense at the service level, but when it come to the network configuration, having the explicit rule that reference the DSCP (and class id) is more cohrent with what is intended from a network model.

In some deployments, the mapping of DSCPs to class is fixed by the SP, and is the same for all customers. So there is not a requirement to state the DSCP mapping in each network order. They simply need to state the percentage for each class (which custom qos in RFC8299 allows you to do).

**Comment by boucadair** [comment]
> In some deployments, the mapping of DSCPs to class is fixed by the SP, and is the same for all customers. So there is not a requirement to state the DSCP mapping in each network order. They simply need to state the percentage for each class (which custom qos in RFC8299 allows you to do)

Sure. I'm not questioning that. The proposal is to use the exiting the existing QoS policy for that purpose as well. The following  information will be thus required:

==
                          +--rw qos {vpn-common:qos}?
                          |  +--rw qos-classification-policy
                          |  |  +--rw rule* [id]
                          |  |     +--rw id                         string
                          |  |     +--rw target-class-id?           string {qos}?
                          |  |     +--rw rate-limit?                decimal64
==

I may understand that we may need to separate the classification vs. policing/shaping rather than defining a single qos-policy container that covers both.

I don't have an objection to define the rate-limiter per class in a new qos-action container under which we can basically echo the above subtree.

**Comment by boucadair** [comment]
Thanks, Julian. 

I finally went with these changes: https://www.ietf.org/rfcdiff?url1=draft-ietf-opsawg-l3sm-l3nm&url2=https://raw.githubusercontent.com/IETF-OPSAWG-WG/l3nm/master/I-D-L3NM/draft-ietf-opsawg-l3sm-l3nm.txt
