### ISSUE TITLE
Review Yang for containers that can directly imported from L3SM

### ISSUE THREAD

**Issue by oscargdd** [IETF-OPSAWG-WG/l3nm#32]
Existing containers from L3SM that are 100% reusable and are 1:1 mapped from L3SM to L3NM can be imported

**Comment by sli35** [comment]
It may be easier to wait for a stability of the tree before starting doing that. That would avoid loss of time in case we need to change our mind for some containers.

**Comment by boucadair** [comment]
@oscargdd: Please close this one.

**Comment by oscargdd** [comment]
Solved with the new common module
