### ISSUE TITLE
How to support multiVPN

### ISSUE THREAD

**Issue by sli35** [IETF-OPSAWG-WG/l3nm#33]
The current model has a site bound to a VPN-service. However, as per L3SM, a site may be part of multiple VPNs using the site-vpn-flavor-multi.
In addition, the current model does not support complex import/export policies as L3SM does using the vpn-policy framework.

**Comment by oscargdd** [comment]
In L3SM there a vpn-policies container.

-rw vpn-policies
         | +--rw vpn-policy* [vpn-policy-id]
         |   +--rw vpn-policy-id  svc-id
         |   +--rw entries* [id]
         |    +--rw id    svc-id
         |    +--rw filter
         |    | +--rw (lan)?
         |    |   +--:(prefixes)
         |    |   | +--rw ipv4-lan-prefix*  inet:ipv4-prefix {ipv4}?
         |    |   | +--rw ipv6-lan-prefix*  inet:ipv6-prefix {ipv6}?
         |    |   +--:(lan-tag)
         |    |    +--rw lan-tag*      string
         |    +--rw vpn
         |      +--rw vpn-id    leafref
         |      +--rw site-role?  identityref

In the l3nm there is a pointer to a profile. Then, the profile is created outside L3NM, e.g. by the IETF-routing-policy yang model. 

Stephane, can you check that this aproach for complex import/export policies is ok?

Suggestion: add some text to explain it in the policy section. Complement the simple examples available.

**Comment by boucadair** [comment]
No follow-up from Sti.
