### ISSUE TITLE
BGP Session under vpn_node (erez proposal) or under vpn_network_access 

### ISSUE THREAD

**Issue by oscargdd** [IETF-OPSAWG-WG/l3nm#36]
Currently the BGP PE-CE session is under vpn_network_access. Erez question is if the session should be defined at vpn_node level and not vpn_network_access

**Comment by boucadair** [comment]
I would maintain it under vpn-network-access as the session is specific to this interface. A pointer to a VRF or a physical interface may be added to bind a session to a specific interface/VRF (if needed, but this can be completed when it comes to passing the network model to a device model).

**Comment by segevere** [comment]
- group decision - to keep in under vpn-network-access 
In the implementation level there the fulfillment entity need to go down to the device and set the BGP per VRF on the device level.  each BGP over vpn-network-access  reflected as a neighbor configuration on the BGP instance on the VRF.
Dual homing is done from different PEs - metric is treated in the customer side .
it apears the local-as is missing in BGP container.

**Comment by boucadair** [comment]
Unless I'm mistaken, this one should be now closed.

**Comment by segevere** [comment]
yes , can be close. It appear that I didn't convince the group .. :(

**Comment by oscargdd** [comment]
Issue closed as per latest comment
