### ISSUE TITLE
Loopback Type Interface

### ISSUE THREAD

**Issue by sbarguil** [IETF-OPSAWG-WG/l3nm#38]
A loopback interface could be considered as a special vpn_network_access. The problem may come when defining the type of vpn_network_access, since it is not point-to-point or multipoint.

**Comment by oscargdd** [comment]
Create a new identity loopback as a new vpn_network_access_type

**Comment by sbarguil** [comment]
Done

https://github.com/IETF-OPSAWG-WG/l3nm/commit/9b56f8ec83ce81a9ae03379480e2301632d05d83

```
  identity loopback {
  base site-network-access-type;
  description
  "Identity for loopback connection.";
```

**Comment by segevere** [comment]
need to add a some text in the where we explain the tree structure.. 
- the creation of loopback is done via device model . 
- in the usecase section we need to explain the motivation for adding loopback to a vpn-node

**Comment by oscargdd** [comment]
Text will be prepared for next version -04)

**Comment by sbarguil** [comment]
#180 includes the change in the text. @segevere can you please give it a review?

**Comment by segevere** [comment]
There is another type that need to be considered: IRB for Integrated Routing Bridge , it is usable when connecting a logical interface between VRF and VSI.
this network access is mutual to L3VPN and L2VPN.

**Comment by sbarguil** [comment]
We have the "pseudowire" type for this case, but I guess we can re-name it to be more clear:
From:

```
  identity pseudowire {
    base site-network-access-type;
    description
      "Identity for pseudowire connections.";
  }

```
To:
```
  identity irb {
    base site-network-access-type;
    description
      "Integrated Routing Bridge. 
Identity for pseudowire connections.";
  
```
What do you think?
