### ISSUE TITLE
Add "hybrid/custom" topology to vpn-service-topology

### ISSUE THREAD

**Issue by oscargdd** [IETF-OPSAWG-WG/l3nm#40]
We have a use case in Telefonica where the topology is more complex (it is not just any-to-any, hub and spoke, or hub and spoke disjoint). Every individual node could be both hub and spoke, or hub, or spoke. The topology will be dictated by the import/export profiles. Hence, the proposal is to add a "hybrid" or "custom" topology identity to reflect the reality.

**Comment by sbarguil** [comment]
07d24bb0c8aecec7c7a0afc151bccf517a51951f

**Comment by oscargdd** [comment]
close, as linked with the routing policy discussion. 

The description of the "custom" identity needs to be improved.

**Comment by sbarguil** [comment]
Rady in #173
