### ISSUE TITLE
Change hierarchy of connection and add new types of connection (pseudowire, vpls, logical)

### ISSUE THREAD

**Issue by oscargdd** [IETF-OPSAWG-WG/l3nm#43]
Currently, under connection there are tagged interface and bearer containers. The proposal is to leave only the connection container and include there all types of connections. Hence, the tagged-interterface type would disapppear and all current tagged-interfaces types could be added in connection . Under connection leave only bearer reference (to include the reference to L3SM). 

Hence, the posible encapsulation types are:
* untagged-interface
*  dot1q-vlan-tagged
*  priority-tagged
* qinq
* qinany
* vxlan

New proposed types are:
* pseudowire (already modeled under bearer). 
* vpls (needs far end ,  vc_id and vpls_service_name)
* logical tunnel interface (needs peer unit as parameter)

**Comment by luciaob** [comment]
In order to define a logical tunnel interface, the vpn-node should be identified as logical-system. To get that identification, we could use the "node-role" parameter to select when a node is a PE (physical), logical (virtual node within a physical router) or even if it is just a VRF-lite role.+

**Comment by sbarguil** [comment]
21688b506ba241ea98582f91658f09337c936069
