### ISSUE TITLE
Add optional BGP_description under BGP_Session

### ISSUE THREAD

**Issue by oscargdd** [IETF-OPSAWG-WG/l3nm#44]
The proposal is to add an optionalBGP_description parameter under BGP_Session. It is useful so when the service is created, the operator can add a custom description to facilitate the service diagnosis.

**Comment by sbarguil** [comment]
Description added

```
           |     |     |     +--rw bgp {rtg-bgp}?
           |     |     |     |  +--rw peer-autonomous-system     inet:as-number
           |     |     |     |  +--rw local-autonomous-system?   inet:as-number
           |     |     |     |  +--rw address-family*            address-family
           |     |     |     |  +--rw neighbor?                  inet:ip-address
           |     |     |     |  +--rw multihop?                  uint8
           |     |     |     |  +--rw security
           |     |     |     |  |  +--rw auth-key?   string
           |     |     |     |  +--rw status
           |     |     |     |  |  +--rw admin-enabled?   boolean
           |     |     |     |  |  +--ro oper-status?     operational-type
```
a17d9ce07deeb502b296346ac72d277c204959e4

**Comment by oscargdd** [comment]
The BGP Description has been added and the description has also been added by med in pull request 2219ab8e93e8a3966a9dede2a4fd3e1e93291088

 leaf description {
        type string;
         description
         "Describes the BGP-Peer Information";
}
