### ISSUE TITLE
Add RP PIM Anycast under multicast configuration 

### ISSUE THREAD

**Issue by oscargdd** [IETF-OPSAWG-WG/l3nm#45]
In the modeling of the Multicast VPN Service for IP TV distribution, we have found that we need to include RP PIM Anycast und. er multicast configuration. It needs:
* source_address
* list of peers
The information needs to be provided by vpn_node.

**Comment by oscargdd** [comment]
To be solved together with issue #47

**Comment by sbarguil** [comment]
It is required to add the following information to detail the Multicast service:

-  Provider Tunnel: 
	RSVP-TE
	mLDP 
-  PMSI-Type: 
	iPMSI 
	sPMSI
-  Threshold rt

**Comment by sbarguil** [comment]
Non-RP routers cn be configured for MSDP, which may be useful in a domain that does not support multicast sources but does support multicast transit

**Comment by oscargdd** [comment]
All the information is included in the latest version of the draft.
