### ISSUE TITLE
interface BW setting

### ISSUE THREAD

**Issue by segevere** [IETF-OPSAWG-WG/l3nm#46]
the model tree as defined in 3.4.  Model tree doesn't have any BW parameters, it is probably missing. 
there is a need to add the qos_profile sub tree undet vpn_network_access

**Comment by sbarguil** [comment]
QoS profile and svc-bandwidth are under vpn_network_access-> Service.

```
    +--rw service
        +--rw svc-input-bandwidth     uint64
        +--rw svc-output-bandwidth    uint64
        +--rw svc-mtu       uint16
        +--rw qos {qos}?
        |  +--rw qos-profile
        |     +--rw (qos-profile)?
        |        +--:(standard)
        |        |  +--rw profile?     -> /l3vpn-ntw/vpn-profiles/valid-provider-identifiers/qos-profile-identifier/id
```

It is that enough?

**Comment by segevere** [comment]
in general it can, but since the policer involves not only CIR also EIR, EBS, CBS, CF, coloring and more, we plan to anyway augment this area with the following attributes:
+-- rw service
|        +–- rw proactive-policer      string //policer profile set multiple parameters   (CIR,EIR, etc. )                                                      
|        +–- rw flow-block-profile     string //egress traffic shaper profile  
|        +–- classes 
         |       +-- rw class [class id]            
                  +-- rw  class–id string          // CoS - can be single or group
                  +-- rw  policer string           //  (CIR,EIR, etc. )   
                  +-- rw  h-policer string       // hierarchical policer

**Comment by oscargdd** [comment]
@Qin to review

**Comment by billwuqin** [comment]
Oscar, I think policer and shaper related functionalities are more related to device level model. See https://tools.ietf.org/html/draft-ietf-rtgwg-qos-model-02. Each vendors or implementors may implement these functionalities in different ways, would it be great to hide these difference from network level.
Therefore I would not suggest to add them in the L3NM model.

**Comment by boucadair** [comment]
This is up to the device model not the network level model. Agreement to not add more parameters at this stage.
