### ISSUE TITLE
Edit mandatory property form RT type

### ISSUE THREAD

**Issue by luciaob** [IETF-OPSAWG-WG/l3nm#52]
Currently, route-target-type leaf has "mandatory true" property. However, since RT does not have such as mandatory characteristic, it does not make sense to have it on the RT type.

       list route-targets{ 
       key route-target;
        leaf route-target {
          type rt-types:route-target;
          description
            "Route Target value";
        }
      description
        "List of Route Targets.";
      }
      leaf route-target-type {
        type rt-types:route-target-type;
        mandatory true;
        description
          "Import/export type of the Route Target.";
      }
    }

**Comment by sbarguil** [comment]
f762d9eca9c576b52408b37f12e4615857886f57

**Comment by boucadair** [comment]
> route-target

Actually, RT is mandatory given that it is the key.

**Comment by luciaob** [comment]
In this case, the idea is that we do not have any route-target, so route-target list would be empty.

**Comment by boucadair** [comment]
Thank you for clarifying but I don't understand the comment.

A route-type must be associated with a type as per RFC8294/RFC4364. I suggest we revert back. 

BTW, we don't need to define vpn-targets. We do only need to say the following:

OLD:
      list route-targets {
        key "route-target";
        leaf route-target {
          type rt-types:route-target;
          description
            "Route Target value";
        }
        description
          "List of Route Targets.";
      }
      leaf route-target-type {
        type rt-types:route-target-type;
        description
          "Import/export type of the Route Target.";
      }
 }

NEW:
      uses rt-types:vpn-route-targets;

**Comment by sbarguil** [comment]
Yes, Med you are right. We have made the rollback. 

Regards
