### ISSUE TITLE
Custom QoS

### ISSUE THREAD

**Issue by boucadair** [IETF-OPSAWG-WG/l3nm#53]
It is perfectly fine to have latency and jitter in the L3SM but at the the L3NM level these are not relevant as these have been taken into account to derive some specific policies. 
===
           |     |        |                 +-rw latency
           |     |        |                 |  +-rw (flavor)?
           |     |        |                 |     +-:(lowest)
           |     |        |                 |     |  +-rw use-lowest-latency?
           |     |        |                 |     |          empty
           |     |        |                 |     +-:(boundary)
           |     |        |                 |        +-rw jitter-boundary?
           |     |        |                 |                uint16
           |     |        |                 +-rw jitter
           |     |        |                 |  +-rw (flavor)?
           |     |        |                 |     +-:(lowest)
           |     |        |                 |     |  +-rw use-lowest-jitter?
           |     |        |                 |     |          empty
           |     |        |                 |     +-:(boundary)
           |     |        |                 |        +-rw latency-boundary?
           |     |        |                 |                uint32
==

**Comment by billwuqin** [comment]
is specific policies part of L3NM? if it is not, it is nice to keep custom QoS, at least standard QoS profile. 
If specific polices can be represented using transport constraints parameters which was proposed in the earlier version of RFC8049, it is also okay to remove them. But one of challenging for transport constraints introduced, is you should enumerate the transport constraints associated with all the connectivity among customer sites, which it not scale, maybe it is a good idea to define them in the separate model.

**Comment by boucadair** [comment]
I don't think it is specific to L3NM. 

custom QoS can be used to select, e.g., a transport profile or whatever activation policy to satisfy those requirements. We don't need to list all those in the L3NM, having a pointer would suffice, IMO.

**Comment by billwuqin** [comment]
works for me, if we have standard QoS profile, we can add a pointer to these QoS profile.

**Comment by oscargdd** [comment]
Removed custom QoS, leaving the standard profile only 3b74db5a029d44e1c51a87c61c9e7a67696fc392

**Comment by sbarguil** [comment]
Several Standard QoS profiles can be attached in several directions. In/out/Both. 

To support this it must be a list instead of a choice:

``
                 |        |  +--rw qos-profile
                 |        |     +--rw qos-profile* [profile]
                 |        |        +--rw profile      -> /l3vpn-ntw/vpn-profiles/valid-provider-identifiers/qos-profile-identifier/id
                 |        |        +--rw direction?   identityref
``

**Comment by sbarguil** [comment]
e2c6c1ca152fd426723fa93636399af2851e9bd4
