### ISSUE TITLE
Match Filter rules 

### ISSUE THREAD

**Issue by boucadair** [IETF-OPSAWG-WG/l3nm#59]
Should we define advanced mach filters (e.g., the operator may not be an exact match) and follow a more structured way (e.g., RFC8519) instead of the one inherited from service module? 

The NEW structure would look like the following:

           |     |        +-rw qos {l3vpn-svc:qos}?
           |     |        |  +-rw qos-classification-policy
           |     |        |  |  +-rw rule* [id]
           |     |        |  |     +-rw id
           |     |        |  |     |       string
           |     |        |  |     +-rw (match-type)?
           |     |        |  |     |  +-:(match-flow)
           |     |        |  |     |  |  +-rw (l3)?
           |     |        |  |     |  |  |  +-:(ipv4)
           |     |        |  |     |  |  |  |  +-rw ipv4
           |     |        |  |     |  |  |  |     +-rw dscp?
           |     |        |  |     |  |  |  |     |       inet:dscp
           |     |        |  |     |  |  |  |     +-rw ecn?
           |     |        |  |     |  |  |  |     |       uint8
           |     |        |  |     |  |  |  |     +-rw length?
           |     |        |  |     |  |  |  |     |       uint16
           |     |        |  |     |  |  |  |     +-rw ttl?
           |     |        |  |     |  |  |  |     |       uint8
           |     |        |  |     |  |  |  |     +-rw protocol?
           |     |        |  |     |  |  |  |     |       uint8
           |     |        |  |     |  |  |  |     +-rw ihl?
           |     |        |  |     |  |  |  |     |       uint8
           |     |        |  |     |  |  |  |     +-rw flags?
           |     |        |  |     |  |  |  |     |       bits
           |     |        |  |     |  |  |  |     +-rw offset?
           |     |        |  |     |  |  |  |     |       uint16
           |     |        |  |     |  |  |  |     +-rw identification?
           |     |        |  |     |  |  |  |     |       uint16
           |     |        |  |     |  |  |  |     +-rw (destination-network)?
           |     |        |  |     |  |  |  |     |  +-:(destination-ipv4-network)
           |     |        |  |     |  |  |  |     |     +-rw destination-ipv4-network?
           |     |        |  |     |  |  |  |     |             inet:ipv4-prefix
           |     |        |  |     |  |  |  |     +-rw (source-network)?
           |     |        |  |     |  |  |  |        +-:(source-ipv4-network)
           |     |        |  |     |  |  |  |           +-rw source-ipv4-network?
           |     |        |  |     |  |  |  |                   inet:ipv4-prefix
           |     |        |  |     |  |  |  +-:(ipv6)
           |     |        |  |     |  |  |     +-rw ipv6
           |     |        |  |     |  |  |        +-rw dscp?
           |     |        |  |     |  |  |        |       inet:dscp
           |     |        |  |     |  |  |        +-rw ecn?
           |     |        |  |     |  |  |        |       uint8
           |     |        |  |     |  |  |        +-rw length?
           |     |        |  |     |  |  |        |       uint16
           |     |        |  |     |  |  |        +-rw ttl?
           |     |        |  |     |  |  |        |       uint8
           |     |        |  |     |  |  |        +-rw protocol?
           |     |        |  |     |  |  |        |       uint8
           |     |        |  |     |  |  |        +-rw (destination-network)?
           |     |        |  |     |  |  |        |  +-:(destination-ipv6-network)
           |     |        |  |     |  |  |        |     +-rw destination-ipv6-network?
           |     |        |  |     |  |  |        |             inet:ipv6-prefix
           |     |        |  |     |  |  |        +-rw (source-network)?
           |     |        |  |     |  |  |        |  +-:(source-ipv6-network)
           |     |        |  |     |  |  |        |     +-rw source-ipv6-network?
           |     |        |  |     |  |  |        |             inet:ipv6-prefix
           |     |        |  |     |  |  |        +-rw flow-label?
           |     |        |  |     |  |  |                inet:ipv6-flow-label
           |     |        |  |     |  |  +-rw (l4)?
           |     |        |  |     |  |     +-:(tcp)
           |     |        |  |     |  |     |  +-rw tcp
           |     |        |  |     |  |     |     +-rw sequence-number?
           |     |        |  |     |  |     |     |       uint32
           |     |        |  |     |  |     |     +-rw acknowledgement-number?
           |     |        |  |     |  |     |     |       uint32
           |     |        |  |     |  |     |     +-rw data-offset?
           |     |        |  |     |  |     |     |       uint8
           |     |        |  |     |  |     |     +-rw reserved?
           |     |        |  |     |  |     |     |       uint8
           |     |        |  |     |  |     |     +-rw flags?
           |     |        |  |     |  |     |     |       bits
           |     |        |  |     |  |     |     +-rw window-size?
           |     |        |  |     |  |     |     |       uint16
           |     |        |  |     |  |     |     +-rw urgent-pointer?
           |     |        |  |     |  |     |     |       uint16
           |     |        |  |     |  |     |     +-rw options?
           |     |        |  |     |  |     |     |       binary
           |     |        |  |     |  |     |     +-rw (source-port)?
           |     |        |  |     |  |     |     |  +-:(source-port-range-or-operator)
           |     |        |  |     |  |     |     |     +-rw source-port-range-or-operator
           |     |        |  |     |  |     |     |        +-rw (port-range-or-operator)?
           |     |        |  |     |  |     |     |           +-:(range)
           |     |        |  |     |  |     |     |           |  +-rw lower-port
           |     |        |  |     |  |     |     |           |  |       inet:port-number
           |     |        |  |     |  |     |     |           |  +-rw upper-port
           |     |        |  |     |  |     |     |           |          inet:port-number
           |     |        |  |     |  |     |     |           +-:(operator)
           |     |        |  |     |  |     |     |              +-rw operator?
           |     |        |  |     |  |     |     |              |       operator
           |     |        |  |     |  |     |     |              +-rw port
           |     |        |  |     |  |     |     |                      inet:port-number
           |     |        |  |     |  |     |     +-rw (destination-port)?
           |     |        |  |     |  |     |        +-:(destination-port-range-or-operator)
           |     |        |  |     |  |     |           +-rw destination-port-range-or-operator
           |     |        |  |     |  |     |              +-rw (port-range-or-operator)?
           |     |        |  |     |  |     |                 +-:(range)
           |     |        |  |     |  |     |                 |  +-rw lower-port
           |     |        |  |     |  |     |                 |  |       inet:port-number
           |     |        |  |     |  |     |                 |  +-rw upper-port
           |     |        |  |     |  |     |                 |          inet:port-number
           |     |        |  |     |  |     |                 +-:(operator)
           |     |        |  |     |  |     |                    +-rw operator?
           |     |        |  |     |  |     |                    |       operator
           |     |        |  |     |  |     |                    +-rw port
           |     |        |  |     |  |     |                            inet:port-number
           |     |        |  |     |  |     +-:(udp)
           |     |        |  |     |  |        +-rw udp
           |     |        |  |     |  |           +-rw length?
           |     |        |  |     |  |           |       uint16
           |     |        |  |     |  |           +-rw (source-port)?
           |     |        |  |     |  |           |  +-:(source-port-range-or-operator)
           |     |        |  |     |  |           |     +-rw source-port-range-or-operator
           |     |        |  |     |  |           |        +-rw (port-range-or-operator)?
           |     |        |  |     |  |           |           +-:(range)
           |     |        |  |     |  |           |           |  +-rw lower-port
           |     |        |  |     |  |           |           |  |       inet:port-number
           |     |        |  |     |  |           |           |  +-rw upper-port
           |     |        |  |     |  |           |           |          inet:port-number
           |     |        |  |     |  |           |           +-:(operator)
           |     |        |  |     |  |           |              +-rw operator?
           |     |        |  |     |  |           |              |       operator
           |     |        |  |     |  |           |              +-rw port
           |     |        |  |     |  |           |                      inet:port-number
           |     |        |  |     |  |           +-rw (destination-port)?
           |     |        |  |     |  |              +-:(destination-port-range-or-operator)
           |     |        |  |     |  |                 +-rw destination-port-range-or-operator
           |     |        |  |     |  |                    +-rw (port-range-or-operator)?
           |     |        |  |     |  |                       +-:(range)
           |     |        |  |     |  |                       |  +-rw lower-port
           |     |        |  |     |  |                       |  |       inet:port-number
           |     |        |  |     |  |                       |  +-rw upper-port
           |     |        |  |     |  |                       |          inet:port-number
           |     |        |  |     |  |                       +-:(operator)
           |     |        |  |     |  |                          +-rw operator?
           |     |        |  |     |  |                          |       operator
           |     |        |  |     |  |                          +-rw port
           |     |        |  |     |  |                                  inet:port-number

**Comment by billwuqin** [comment]
Sounds reasonable to me, we should support flow match and application match.

**Comment by oscargdd** [comment]
Closed with pull request #88
