### ISSUE TITLE
Link to the L3SM 

### ISSUE THREAD

**Issue by boucadair** [IETF-OPSAWG-WG/l3nm#61]
#60 

Allows a controller to expose the L3SM to which an L3NM is bound

**Comment by oscargdd** [comment]
OK! It is optional. Should work typically the other way around, allows the service orchestrator to maintain the match and facilitate reconciliation. 
@boucadair Please add some text in the draft to explain the parameter

**Comment by boucadair** [comment]
Please see the change: #72

Will add more text once we will work seriously on the tree structure part.
