### ISSUE TITLE
Overall Service Status

### ISSUE THREAD

**Issue by boucadair** [IETF-OPSAWG-WG/l3nm#62]
see #58 

        +--rw vpn-service* [vpn-id]
           +--rw service-status
           |  +--rw admin
           |  |  +--rw status?      operational-type
           |  |  +--rw timestamp?   yang:date-and-time
           |  +--ro ops
           |     +--ro status?      operational-type
           |     +--ro timestamp?   yang:date-and-time

**Comment by oscargdd** [comment]
OK! Please review the change request, you need to delete a grouping service-status.

**Comment by oscargdd** [comment]
closed with pull request https://github.com/IETF-OPSAWG-WG/l3nm/pull/58/commits/b75a59cce94920742b149d03d5de60b89a54bfc1
