### ISSUE TITLE
Capabilities

### ISSUE THREAD

**Issue by boucadair** [IETF-OPSAWG-WG/l3nm#71]
Consider exposing a set of VPN-related network capabilities. These capabilities may be used by the service layer as input to service order handling (or service activation).

**Comment by oscargdd** [comment]
examples?

**Comment by boucadair** [comment]
Examples can be:
* Limit on max routes per customer: supported/not
* FIB/RIB limits
* Max supported VRF instances
* link capacity
* Max BGP sessions
* Encryption capabilities

**Comment by oscargdd** [comment]
Interesting, but we do not know if it fits here. It is an step before provision. Let’s see where is the best place to fit the information.
Is the information per network node?
If the information is per node, it is more an "inventory-like" capability. It might fit better in the uni-topology draft. Thoughts?

**Comment by segevere** [comment]
just an idea,... as we have the VPN-profiles which declare the profiles that can be used by OSS in service creation payload, we can define vpn-capabilities that publish the controllers capabilities.

**Comment by oscargdd** [comment]
Agreement on not to be included in L3NM, It is considered useful to expose some capabilities to facilitate the orchestration, but it Will be in a separate line of work.
