### ISSUE TITLE
singleaddress under Multicast-RP

### ISSUE THREAD

**Issue by sbarguil** [IETF-OPSAWG-WG/l3nm#83]
RP-group address is usually an IP/prefix not a single IP address:

![image](https://user-images.githubusercontent.com/13772485/75152262-ec0f4500-5708-11ea-81d8-772356e11474.png)

**Example:**
`group-prefix 239.130.0.0/15`

Suggestion to change "singleaddress" for "prefix-address" or "group-prefix"

**Comment by luciaob** [comment]
Parameter has been updated, this is the new tree view:

![image](https://user-images.githubusercontent.com/60645253/75173110-ad8c8100-572e-11ea-8a83-54c609c867c2.png)

**Comment by sbarguil** [comment]
254e606eeb6316338a31b5d1b6781dd13b1c0127
