### ISSUE TITLE
Clarify the augmentations to L3SM

### ISSUE THREAD

**Issue by PhilipEardley** [IETF-OPSAWG-WG/l3nm#9]
It is hard to understand what the additions to L3SM are, since Section 4 seems to include the L3SM wholesale (is this needed?). Can at least the augmentations be listed separately please.

**Comment by oscargdd** [comment]
New versión of the text is done in versión -01. There the model is clarified.

**Comment by sli35** [comment]
We are not augmenting L3SM, but we are building a new model which reuses partially L3SM.
The parameters that need to be transparently passed from L3SM to L3NM may be clarified later when we will have a better view and when the tree will be stable.

**Comment by oscargdd** [comment]
@PhilipEardley If you are OK, we can close this issue, as there are no augmenations as explained by Stephane, and keep open issue #32 to identify the L3SM->L3NM mappings

**Comment by PhilipEardley** [comment]
Sorry, not had time to think about this
phil

**Comment by oscargdd** [comment]
Closed issue as there are no augmentations to L3SM. The relations between L3SM and L3NM have been clarified.
